/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _puzzleorginal_h_
#define _puzzleorginal_h_
//---------------------------------------------------------------------------------
extern const unsigned char puzzleorginal[];
extern const int puzzleorginal_size;
//---------------------------------------------------------------------------------
#endif //_puzzleorginal_h_
//---------------------------------------------------------------------------------
